name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: meiko
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://x-access-token:${{ secrets.GITHUB_TOKEN }}@git.miku/${{ github.repository }}.git .

      - name: Build
        run: |
          buildah bud -t git.miku/${{ github.repository }}:main .
      - name: Push
        run: |
          buildah login -u ${{ github.actor }} -p ${{ secrets.PACKAGEPUSH }} git.miku
          buildah push git.miku/${{ github.repository }}:main
