name: Autoscrape
on:
  schedule:
    - cron: '0 10 * * Tue,Wed' # At 10:00, only on Tuesday and Wednesday
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: "lvchart-update[bot]"
  GIT_AUTHOR_EMAIL: "lvchart-update[bot]@git.miku"
  GIT_COMMITTER_NAME: "lvchart-update[bot]"
  GIT_COMMITTER_EMAIL: "lvchart-update[bot]@git.miku"

jobs:
  scrape:
    runs-on: meiko
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://x-access-token:${{ secrets.GITHUB_TOKEN }}@git.miku/${{ github.repository }}.git .

      - name: Install build deps
        run: |
          dnf -y upgrade
          dnf -y install meson g++ libcurl-devel zlib-ng-devel openssl-devel systemd-devel git cmake cpr-devel file-devel

      - name: Build
        run: |
          meson setup build -Dbuild_anidb_sourcegen=true -Dcpp_std=c++26
          meson compile -C build vocadb-scraper

      - name: Run chart update
        run: |
          build/src/vocadb/vocadb-scraper

      - name: Check for change
        id: has_change
        run: |
          if git diff --quiet; then
            echo NO CHANGE
            echo "changed=false" >> $FORGEJO_OUTPUT
          else
            echo Change:
            git status
            echo "changed=true" >> $FORGEJO_OUTPUT
          fi

      - name: Commit
        if: steps.has_change.outputs.changed == 'true'
        run: |
          git add -u
          git add res/localvoid/*.json
          git commit -m 'Auto Scraper Update'
          git push

  trigger-songbot-build:
    runs-on: meiko
    needs: scrape
    uses: ./.forgejo/workflows/docker-build.yml
    secrets: inherit
