/*
    Songbot: Hatsune Miku Concert Database for Discord
    Copyright (C) 2025  Andrew Potter

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

export module project_sekai:tracks;

import :types;
import std;
import songs;
import songbot.errors;
import util;

namespace {
  constexpr auto no = std::nullopt;
}

export constexpr std::array sekai_tracks = std::to_array<SekaiTrack>({
    /* Pre-Existing Songs */
    { 1, VSG,     "Tell Your World" },
    { 43, VSG,    "Next Nest" },
    { 44, VSG,    "Hand in Hand" },
    { 45, VSG,    "39 Music!" },
    { 46, VSG,    "Greenlights Serenade" },
    { 47, VSG,    "Melt" },
    { 48, VSG,    "World is Mine" },
    { 49, VSG,    "Hatsune Miku no Shoushitsu" },
    { 50, VSG,    "Blessing" },
    { 72, VSG,    "Bless Your Breath" },
    { 83, VSG,    "Gimme×Gimme" },
    { 84, VSG,    "Junky Night Town Orchestra" },
    { 85, VSG,    "Leia - Remind" },
    { 86, VSG,    "on the rocks" },
    { 10001, VSG, "Jangsanbeom" },
    { 10002, VSG, "Alone" },
    { 10003, VSG, "Gakgaejeontu" },
    { 10004, VSG, "Beotkkotbi" },
    { 10005, VSG, "Byeolbit Serenade" },
    { 10006, VSG, "Bimil Inhyeonggeuk II" },
    { 10007, VSG, "Carpe Diem!" },
    { 10008, VSG, "Dungap" },
    { 10009, VSG, "Usan" },
    { 10010, VSG, "Shimiyuku" },
    { 104, VSG,   "Cendrillon 10th Anniversary" },
    { 108, VSG,   "Aisarenakute mo Kimi ga Iru" },
    { 109, VSG,   "Hibikase" },
    { 110, VSG,   "Senbonzakura" },
    { 11001, VSG, "Pick Me Up" },
    { 11002, VSG, "My Stage With You" },
    { 11003, VSG, "Tàbù, Chūfā" },
    { 11004, VSG, "Chūlán" },
    { 11005, VSG, "We Leave The World Together" },
    { 11006, VSG, "Jìng Zhōng Shàonǚ" },
    { 11007, VSG, "Mèngsè Xīngqiú" },
    { 11010, VSG, "Yuèguò Hǎi'ànxiàn" },
    { 11012, VSG, "Lái Dōu Lái le" },
    { 11013, VSG, "HIMAN=HIDAI Syousoukyoku" },
    { 11014, VSG, "Yuè Xī Jiāng · Chūnléi" },
    { 11015, VSG, "Mǎi Mǎi Mǎi" },
    { 11016, VSG, "Mag1c" },
    { 113, VSG,   "Rolling Girl" },
    { 114, VSG,   "Ura Omote Lovers" },
    { 115, VSG,   "Unknown Mother Goose" },
    { 117, VSG,   "ODDS&ENDS" },
    { 118, VSG,   "＊Hello, Planet." },
    { 119, VSG,   "World's End Dancehall" },
    { 124, VSG,   "Miku Miku ni Shite Ageru♪ (Shite Yan Yo)" },
    { 131, VSG,   "Hatsune Miku no Gekishou" },
    { 150, VSG,   "TOKIO FUNKA" },
    { 152, VSG,   "Dareka no Shinzou ni Nareta Nara" },
    { 153, VSG,   "Miku" },
    { 175, VSG,   "Haikei Doppelganger" },
    { 177, VSG,   "Migikata no Chou" },
    { 179, VSG,   "Roshin Yuukai" },
    { 186, VSG,   "Hatsune Tenchikaibyaku Shinwa" },
    { 190, VSG,   "Aku no Musume" },
    { 191, VSG,   "Aku no Meshitsukai" },
    { 202, VSG,   "Q" },
    { 206, VSG,   "Kimiiro Marine Snow" },
    { 214, VSG,   "Palette ni wa Kimi ga Ippai" },
    { 216, VSG,   "Luka Luka ★ Night Fever" },
    { 219, VSG,   "Suna no Wakusei" },
    { 220, VSG,   "Donut Hole 2024" },
    { 220, VSG,   "Donut Hole" },
    { 221, VSG,   "Matryoshka" },
    { 222, VSG,   "Piano×Forte×Scandal" },
    { 223, VSG,   "Sennen no Dokusouka" },
    { 228, VSG,   "Goodbye" },
    { 229, VSG,   "Noushou Sakuretsu Girl" },
    { 238, VSG,   "Black ★ Rock Shooter" },
    { 247, VSG,   "Copycat" },
    { 249, VSG,   "Bokura no 16bit Sensou" },
    { 250, VSG,   "Kusaregedou to Chocolate" },
    { 251, VSG,   "Fräulein=Biblioteca" },
    { 256, VSG,   "Double Lariat" },
    { 261, VSG,   "Hoshikuzu Utopia" },
    { 263, VSG,   "Highlight" },
    { 265, VSG,   "Change me" },
    { 271, VSG,   "Attakaito" },
    { 273, VSG,   "FUTURE EVE" },
    { 275, VSG,   "Paradichlorobenzene" },
    { 278, VSG,   "Bad ∞ End ∞ Night" },
    { 279, VSG,   "Kochira, Koufuku Anshin Iinkai Desu." },
    { 283, VSG,   "Rainy Snowdrop" },
    { 284, VSG,   "Invisible" },
    { 288, VSG,   "Unhappy Refrain" },
    { 296, VSG,   "Cantarella" },
    { 297, VSG,   "p.h." },
    { 301, VSG,   "Watashi no Koi wa Hellfire" },
    { 303, VSG,   "Rin-chan Now!" },
    { 305, VSG,   "Strobe Last" },
    { 309, VSG,   "Afterglow" },
    { 311, VSG,   "Yoake to Hotaru" },
    { 312, VSG,   "Kokoro" },
    { 313, VSG,   "FREELY TOMORROW" },
    { 317, VSG,   "Mahou Mitai na Music!" },
    { 318, VSG,   "Sharing The World" },
    { 319, VSG,   "Decade" },
    { 325, VSG,   "Buta ni Natte yeah yeah" },
    { 326, VSG,   "Tenshi no Tsubasa." },
    { 327, VSG,   "SnowMix♪" },
    { 328, VSG,   "SEKAI-chan to KAFU-chan no Otsukai Gassoukyoku" },
    { 330, VSG,   "Interviewer" },
    { 331, VSG,   "39" },
    { 334, VSG,   "Vampire's ∞ pathoS" },
    { 335, VSG,   "TRASH and TRASH!" },
    { 337, VSG,   "METEOR" },
    { 341, VSG,   "Nanchoukei Danshi ga Taosenai" },
    { 342, VSG,   "Blue Star" },
    { 343, VSG,   "Snowman" },
    { 347, VSG,   "Enbizaka no Shitateya" },
    { 348, VSG,   "Akutoku no Judgement" },
    { 349, VSG,   "Akujiki Musume Conchita" },
    { 350, VSG,   "Nemurase Hime kara no gift" },
    { 357, VSG,   "Blue Planet" },
    { 362, VSG,   "Wonder Style" },
    { 363, VSG,   "UNDERWATER" },
    { 371, VSG,   "Sweety glitch" },
    { 379, VSG,   "Zunda Party Night" },
    { 381, VSG,   "Shinjinrui" },
    { 387, VSG,   "Hello Builder" },
    { 388, VSG,   "Hatsune Miku no Gekishou" },
    { 390, VSG,   "Dear" },
    { 401, VSG,   "Manimani" },
    { 403, VSG,   "Tsugai Kogarashi" },
    { 412, VSG,   "Devil Janai Mon" },
    { 414, VSG,   "HERO" },
    { 415, VSG,   "Lucky☆Orb" },
    { 419, VSG,   "Unsung Melodies" },
    { 420, VSG,   "Imaginary love story" },
    { 430, VSG,   "\"Nh-Uh-Uh.\"" },
    { 433, VSG,   "Hiasobi" },
    { 435, VSG,   "Relay Outer" },
    { 439, VSG,   "Issen Kounen" },
    { 453, VSG,   "Ten Thousand Stars" },
    { 454, VSG,   "Electric Angel" },
    { 459, VSG,   "Can't Make A Song!!" },
    { 461, VSG,   "Odorobo" },
    { 462, VSG,   "Red Land Marker" },
    { 463, VSG,   "Happy Cheat Day" },
    { 464, VSG,   "Intergalactic Bound" },
    { 466, VSG,   "Garnet no Namida" },
    { 467, VSG,   "Ai no Uta" },
    { 470, VSG,   "Hajimete no Oto" },
    { 479, VSG,   "MikuFiesta" },
    { 483, VSG,   "A Kotoba" },
    { 485, VSG,   "Dandan Hayaku Naru" },
    { 502, VSG,   "Help me, ERINNNNNN!!" },
    { 515, VSG,   "Igaku" },
    { 516, VSG,   "Achikochi Date-san" },
    { 518, VSG,   "Mikaboshi" },
    { 523, VSG,   "Kimi to Boku no Resonance" },
    { 525, VSG,   "Antenna 39" },
    { 528, VSG,   "Thousand Little Voices" },
    { 529, VSG,   "culture" },
    { 531, VSG,   "Mesmerizer" },
    { 535, VSG,   "Plaything" },
    { 541, VSG,   "Main Character" },
    { 542, VSG,   "Blackjack" },
    { 552, VSG,   "M@GICAL☆CURE! LOVE ♥ SHOT!" },
    { 558, VSG,   "No da" },
    { 561, VSG,   "Proto Disco" },
    { 562, VSG,   "Ángel" },
    { 563, VSG,   "NAKAKAPAGPABAGABAG" },
    { 566, VSG,   "Panda Hero" },
    { 567, VSG,   "Musunde Hiraite Rasetsu to Mukuro" },
    { 568, VSG,   "Just 1dB Louder" },
    { 584, VSG,   "IMAWANOKIWA" },
    { 589, VSG,   "Barerii Ko" },
    { 590, VSG,   "MANHATTAN" },
    { 591, VSG,   "Yoshiwara Lament Sairaiban" },
    { 592, VSG,   "Queen of Hearts" },
    { 593, VSG,   "Crystal Snow" },
    { 594, VSG,   "Call!!" },
    { 598, VSG,   "Last of Me" },
    { 599, VSG,   "Karma" },
    { 604, VSG,   "Packaged" },
    { 609, VSG,   "Sad Machine" },
    { 611, VSG,   "Suki! Yuki! Maji Magic" },
    { 612, VSG,   "Snow Fairy Story" },
    { 613, VSG,   "Yuki ga Tokeru Mae ni" },
    { 614, VSG,   "Star Night Snow" },
    { 615, VSG,   "Shikakui Chikyuu wo Maruku Suru" },
    { 616, VSG,   "AI" },
    { 617, VSG,   "Pokapoka no Hoshi" },
    { 618, VSG,   "Fondant Step" },
    { 619, VSG,   "Connecting" },
    { 624, VSG,   "Cirno no Perfect Sansuu Gakuen" },
    { 627, VSG,   "TETORIS" },
    { 628, VSG,   "Monitoring" },
    { 638, VSG,   "Kaben, Sore ni Matsuwaru Onsei" },
    { 639, VSG,   "Marionette Dancer" },
    { 640, VSG,   "MONSTER" },
    { 648, VSG,   "Life Will Change" },
    { 651, VSG,   "White Happy" },
    { 652, VSG,   "Kareshi no Jude" },
    { 653, VSG,   "Pamela" },
    { 654, VSG,   "Lustrous" },
    { 657, VSG,   "i DO what i WANT" },
    { 658, VSG,   "Jougen no Tsuki" },
    { 663, VSG,   "Venus" },
    { 666, VSG,   "Shoujo A" },
    { 667, VSG,   "Musekinin Shuugoutai" },
    { 669, VSG,   "Genten" },
    { 685, VSG,   "DENKOH SEKKA" },
    { 686, VSG,   "TREASURE GARDEN" },
    { 687, VSG,   "JET BLACK" },
    { 688, VSG,   "WE ARE PICO PICO HAMMERS!!!!" },
    { 689, VSG,   "SAI'AI JINSEI RUNNER" },
    { 692, VSG,   "Vocalo-Colosseum" },
    { 694, VSG,   "Artifact" },
    { 699, VSG,   "Catch the Wave" },
    { 704, VSG,   "Kuronuri Sekai ate Shokan" },
    { 709, VSG,   "Hatsune Miku no Shoushitsu-Gekijouban-" },
    { 711, VSG,   "Wanderlast" },
    { 713, VSG,   "Nyanyanyanyanyanyanya!" },
    { 714, VSG,   "Fräulein=Ojousama" },
    { 717, VSG,   "Ribbon" },
    { 718, VSG,   "Maku wo Orosou, Parade e" },
    { 719, VSG,   "SHIAWASE FOR YOU!" },
    { 721, VSG,   "Aishiteitanoni" },
    { 722, VSG,   "Daidaidaidaidaikirai" },
    { 724, VSG,   "Hao" },
    { 725, VSG,   "shrimp miku" },
    { 726, VSG,   "Alkali Rettousei" },
    { 727, VSG,   "T-shi no Hanashi wo Shinjiru na" },
    { 736, VSG,   "LOVELY CAVITY" },
    { no, VSG,    "Hikari no Atsumekata" },
    { no, VSG,    "Lapse" },
    { no, VSG,    "De Los Santos" },
    { no, VSG,    "Ichiokunen Koi Shiteru" },
    { no, VSG,    "Ima Sugu Rinne" },
    /* Cover Songs */
    { 2, LEO,     "Roki" },
    { 3, LEO,     "Teo" },
    { 6, LEO,     "Hibana -Reloaded-" },
    { 8, LEO,     "Time Machine" },
    { 10, MMJ,    "Happy Synthesizer" },
    { 11, MMJ,    "Viva Happy" },
    { 13, MMJ,    "Nostalogic" },
    { 15, VBS,    "drop pop candy" },
    { 18, LEO,    "Asu no Yozora Shoukaihan" },
    { 19, N25,    "Charles" },
    { 21, WxS,    "Dappou Rock" },
    { 22, N25,    "Inochi ni Kirawarete Iru" },
    { 26, VBS,    "Rettou Joutou" },
    { 27, VBS,    "Just Be Friends" },
    { 28, VBS,    "Doctor=Funk Beat" },
    { 36, WxS,    "Miracle Paint" },
    { 38, WxS,    "Buriki no Dance" },
    { 41, WxS,    "Sweet Magic" },
    { 66, N25,    "Hello／How Are You" },
    { 67, N25,    "Jishou Mushoku" },
    { 68, WxS,    "Dance Robot Dance" },
    { 69, VBS,    "Fragile" },
    { 70, MMJ,    "Melty Land Nightmare" },
    { 71, MMJ,    "Tsugihagi Staccato" },
    { 73, MMJ,    "Near" },
    { 74, N25,    "Hitorinbo Envy" },
    { 75, LEO,    "Umiyuri Kaiteitan" },
    { 78, WxS,    "Bouken no Sho ga Kiemashita!" },
    { 81, VBS,    "Yobanashi Deceive" },
    { 87, MMJ,    "Ren'ai Saiban" },
    { 88, WxS,    "Chururira Chururira Daddadda!" },
    { 91, LEO,    "Dramaturgy" },
    { 92, N25,    "Otome Kaibou" },
    { 93, LEO,    "Aoku Kakero!" },
    { 94, N25,    "Totemo Itai Itagaritai" },
    { 95, VBS,    "Ifuudoudou" },
    { 96, LEO,    "from Y to Y" },
    { 98, LEO,    "Lost One no Goukoku" },
    { 100, VBS,   "ECHO" },
    { 102, VBS,   "Yuurei Tokyo" },
    { 106, WxS,   "Oki ni Mesu mama" },
    { 107, MMJ,   "Milk Crown on Sonechka" },
    { 111, N25,   "Cutlery" },
    { 120, LEO,   "Ikanaide" },
    { 121, MMJ,   "Romeo to Cinderella" },
    { 122, WxS,   "Positive☆Dance Time" },
    { 123, MMJ,   "Dreamin Chuchu" },
    { 125, N25,   "Bocca della Verità" },
    { 129, N25,   "Bitter Choco Decoration" },
    { 133, VBS,   "Akuma no Odorikata" },
    { 134, WxS,   "Telecaster B-Boy" },
    { 135, LEO,   "Roku-chou Nen to Ichiya Monogatari" },
    { 136, VBS,   "Children Record" },
    { 138, WxS,   "KING" },
    { 139, N25,   "Yoru ni Kakeru" },
    { 143, VBS,   "Traffic Jam" },
    { 145, N25,   "Venom" },
    { 146, WxS,   "Rimokon" },
    { 147, MMJ,   "Karakuri Pierrot" },
    { 148, LEO,   "ray" },
    { 154, MMJ,   "Chikyuu Saigo no Kokuhaku wo" },
    { 155, LEO,   "Shinpakusuu♯0822" },
    { 157, MMJ,   "Marshmary" },
    { 158, WxS,   "Nonsense Bungaku" },
    { 167, VBS,   "Alter Ego" },
    { 168, MMJ,   "Darling Dance" },
    { 169, MMJ,   "Shoujorei" },
    { 170, N25,   "villain" },
    { 171, LEO,   "Kagerou Daze" },
    { 172, MMJ,   "Happy Halloween" },
    { 174, WxS,   "Yī Èr Fanclub" },
    { 181, N25,   "Aishite Aishite Aishite" },
    { 183, WxS,   "fixer" },
    { 184, LEO,   "Hello,world!" },
    { 188, MMJ,   "Kokoroyohou" },
    { 194, N25,   "Mousou Kanshou Daishou Renmei" },
    { 195, VBS,   "PaⅢ.SENSATION" },
    { 198, WxS,   "Goodbye Sengen" },
    { 199, LEO,   "Ghost Rule" },
    { 200, VBS,   "Garando" },
    { 201, WxS,   "Kami no Manimani" },
    { 204, N25,   "Usseewa" },
    { 205, VBS,   "Odo" },
    { 208, LEO,   "Bokura Mada Underground" },
    { 210, VBS,   "Ame to Petra" },
    { 213, MMJ,   "Vampire" },
    { 218, N25,   "Meru" },
    { 225, WxS,   "Ego Rock" },
    { 226, LEO,   "Lost and Found" },
    { 240, WxS,   "Odore Orchestra" },
    { 241, LEO,   "Asagao no Chiru Koro ni" },
    { 242, MMJ,   "Torinoko City" },
    { 243, LEO,   "Calc." },
    { 245, VBS,   "Aun no Beats" },
    { 246, WxS,   "Alien Alien" },
    { 253, VBS,   "DAYBREAK FRONTLINE" },
    { 255, LEO,   "Yomosugara Kimi Omou" },
    { 258, MMJ,   "Shinkai Shoujo" },
    { 260, WxS,   "Love ka?" },
    { 262, VBS,   "Teikoku Shoujo" },
    { 266, VBS,   "YY" },
    { 268, N25,   "Non-breath oblige" },
    { 269, MMJ,   "Lonely Universe" },
    { 270, N25,   "Deichuu ni Saku" },
    { 272, N25,   "Gehenna" },
    { 276, VBS,   "SHANTI" },
    { 277, N25,   "phony" },
    { 281, MMJ,   "Kimagure Mercy" },
    { 286, LEO,   "Hello, Worker" },
    { 289, LEO,   "Amanojaku" },
    { 291, VBS,   "Pheles" },
    { 293, N25,   "Irony" },
    { 294, N25,   "Sore ga Anata no Shiawase to Shite mo" },
    { 298, WxS,   "Netoge Haijin Sprechchor" },
    { 299, VBS,   "Egoist" },
    { 306, WxS,   "1925" },
    { 307, WxS,   "Okochama Sensou" },
    { 320, MMJ,   "Booo!" },
    { 321, LEO,   "Attract Light" },
    { 322, VBS,   "Taemanaku Aiiro" },
    { 323, LEO,   "Kaisei" },
    { 339, LEO,   "glow" },
    { 340, N25,   "Totemo Suteki na Rokugatsu Deshita" },
    { 344, VBS,   "Nounai Kakumei Girl" },
    { 346, WxS,   "Aa, Subarashiki Nyansei" },
    { 352, N25,   "Inochi Bakkari" },
    { 354, MMJ,   "Setsuna Trip" },
    { 355, MMJ,   "Shiroi Yuki no Princess wa" },
    { 358, N25,   "kokoronashi" },
    { 360, WxS,   "Taiyoukei Disco" },
    { 361, MMJ,   "Kyuukurarin" },
    { 365, VBS,   "Koi wa Sensou" },
    { 367, WxS,   "Sukina Koto Dake de Ii Desu" },
    { 369, MMJ,   "Melancholic" },
    { 372, LEO,   "Tengaku" },
    { 376, WxS,   "Wagamama Hime" },
    { 377, MMJ,   "Akuyaku ni Kiss Scene wo" },
    { 378, N25,   "Slow Downer" },
    { 385, N25,   "Kamippoi na" },
    { 391, N25,   "Cute na Kanojo" },
    { 392, VBS,   "Shunran" },
    { 395, LEO,   "Summertime Record" },
    { 396, LEO,   "Tokyo Teddy Bear" },
    { 402, N25,   "Envy Baby" },
    { 407, LEO,   "Hajimete no Koi ga Owaru Toki" },
    { 410, VBS,   "Marshall Maximizer" },
    { 413, MMJ,   "Sayonara Princess" },
    { 417, MMJ,   "Kuu ni Naru" },
    { 418, VBS,   "Kinmokusei" },
    { 431, MMJ,   "flos" },
    { 432, WxS,   "Kyoufuu All Back" },
    { 434, WxS,   "1000-nen Ikiteru" },
    { 436, WxS,   "Kosho Yashiki Satsujin Jiken" },
    { 437, VBS,   "E? Aa, Sou." },
    { 438, LEO,   "Hide and Seek" },
    { 441, VBS,   "Yoidore Shirazu" },
    { 443, LEO,   "Ringo Uri no Utakata Shoujo" },
    { 451, N25,   "Netsu Ijou" },
    { 455, N25,   "Dokuzu" },
    { 456, LEO,   "Kibou no Tsuki" },
    { 458, LEO,   "Batsubyou" },
    { 469, N25,   "Lag Train" },
    { 473, N25,   "Mind Brand" },
    { 475, WxS,   "Chigau!!!" },
    { 476, N25,   "Shadow Shadow" },
    { 477, LEO,   "Mozaik Role (Reloaded)" },
    { 480, WxS,   "Ochame Kinou" },
    { 482, MMJ,   "Dame Ningen da!" },
    { 484, LEO,   "Henceforth" },
    { 490, VBS,   "Rumor" },
    { 491, N25,   "Cat Loving" },
    { 493, WxS,   "Kyou mo Harebare" },
    { 494, MMJ,   "Poppin' Candy☆Fever!" },
    { 495, MMJ,   "Superhero" },
    { 499, WxS,   "Konton Boogie" },
    { 501, N25,   "Bad Apple!! feat.SEKAI" },
    { 505, VBS,   "Call Boy" },
    { 506, WxS,   "QUEEN" },
    { 509, WxS,   "Liar Dancer" },
    { 510, N25,   "Shippaisaku Shoujo" },
    { 511, MMJ,   "Kisaragi Attention" },
    { 513, VBS,   "CH4NGE" },
    { 520, LEO,   "Toumei Elegy" },
    { 521, MMJ,   "Override" },
    { 522, VBS,   "WAVE" },
    { 530, MMJ,   "Cat Food" },
    { 533, WxS,   "Tensei Ringo" },
    { 534, LEO,   "World Lampshade [reunion]" },
    { 536, OTHER, "Fire◎Flower (Rerec)" },
    { 537, VBS,   "Hana ni Kaze" },
    { 544, MMJ,   "Mousou Aspartame" },
    { 547, LEO,   "Shuuen Touhikou" },
    { 551, N25,   "Lost Umbrella" },
    { 554, MMJ,   "snooze" },
    { 556, N25,   "Saihate" },
    { 557, VBS,   "Hana Obore" },
    { 559, LEO,   "Odoryanse" },
    { 571, VBS,   "Nisemono Ningen 40-gou" },
    { 580, VBS,   "Mikazuki Step" },
    { 581, WxS,   "Chuubyou Gekihatsu Boy" },
    { 586, VBS,   "Yankee Boy・Yankee Girl" },
    { 595, LEO,   "ENVY CAT WALK" },
    { 601, MMJ,   "Ruma" },
    { 603, WxS,   "Do Re Mi Fa Rondo" },
    { 606, N25,   "Suicide Parade" },
    { 607, MMJ,   "Mawaru Sora Usagi" },
    { 620, VBS,   "Shama" },
    { 621, MMJ,   "Tokyo Summer Session" },
    { 623, WxS,   "Touhou☆Wonderland" },
    { 625, WxS,   "Kono Fuzaketa Subarashiki Sekai wa, Boku no Tame ni Aru" },
    { 629, MMJ,   "8.32" },
    { 632, VBS,   "Surges" },
    { 641, LEO,   "Kimi ga Tobioriru no Naraba" },
    { 643, VBS,   "About me" },
    { 644, N25,   "Ikiru" },
    { 645, LEO,   "Shinkai City Underground" },
    { 650, N25,   "Ano Natsu ga Houwa Suru." },
    { 661, WxS,   "Hikyou Sentai Urotander" },
    { 664, WxS,   "Hito Mania" },
    { 665, LEO,   "Rocket Cider" },
    { 670, WxS,   "I~ya I~ya I~ya" },
    { 672, VBS,   "How-To Sekai Seifuku" },
    { 680, N25,   "Who?" },
    { 682, MMJ,   "Anata Shika Mienai no" },
    { 690, WxS,   "Wakusei Loop" },
    { 693, MMJ,   "erase or zero" },
    { 698, N25,   "Kusari no Shoujo-Re Alive-" },
    { 700, MMJ,   "Mahou Shoujo to Chocolate" },
    { 702, LEO,   "Ramune" },
    { 703, VBS,   "Violence Trigger" },
    { 710, LEO,   "Hedgehog" },
    { 712, N25,   "Hikaku Shoukougun" },
    { 715, WxS,   "Mahou Shoujo Koufukuron" },
    { 723, N25,   "Lavie" },
    { no, N25,    "Propose" },
    { no, LEO,    "Raspberry＊Monster" },
    { no, VBS,    "Eien Hanahadashii" },
    /* Commissioned Songs */
    { 51, WxS,    "Sekai wa Mada Hajimatte sura Inai" },
    { 52, WxS,    "potato ni Natte iku" },
    { 54, VBS,    "Ready Steady" },
    { 55, VBS,    "Forward" },
    { 57, MMJ,    "Idol Shin'eitai" },
    { 60, N25,    "Kuyamu to Kaite Mirai" },
    { 61, N25,    "Keitai Renwa" },
    { 62, N25,    "Jackpot Sad Girl" },
    { 63, LEO,    "needLe" },
    { 64, LEO,    "Stella" },
    { 76, OTHER,  "SEKAI" },
    { 77, OTHER,  "Wah Wah World" },
    { 89, MMJ,    "Color of Drops" },
    { 90, N25,    "Kagirinaku Haiiro e" },
    { 97, LEO,    "Hare wo Matsu" },
    { 99, MMJ,    "More! Jump! More!" },
    { 101, VBS,   "RAD DOGS" },
    { 103, WxS,   "NIJIIRO STORIES" },
    { 105, WxS,   "Once Upon a Dream" },
    { 11008, VSG, "Yīyàng" },
    { 11017, VSG, "Hype Dive" },
    { 112, MMJ,   "Tenshi no Clover" },
    { 116, N25,   "IDSMILE" },
    { 126, VBS,   "Cinema" },
    { 127, WxS,   "Tondemo-Wonderz" },
    { 130, LEO,   "From Tokyo" },
    { 132, LEO,   "「１」" },
    { 140, MMJ,   "Ice Drop" },
    { 141, OTHER, "Gunjou Sanka" },
    { 142, N25,   "Saisei" },
    { 144, MMJ,   "Ai no Material" },
    { 149, N25,   "Kanadetomosusora" },
    { 156, VBS,   "Beat Eater" },
    { 159, LEO,   "STAGE OF SEKAI" },
    { 160, WxS,   "Showtime Ruler" },
    { 161, VSG,   "magic number" },
    { 166, WxS,   "Glory Steady Go!" },
    { 173, LEO,   "Ryuusei no Pulse" },
    { 176, VSG,   "MACHINEGUN POEM DOLL" },
    { 178, WxS,   "Niccori^^Chousa-tai no Theme" },
    { 180, VBS,   "Mirai" },
    { 182, VBS,   "Flyer!" },
    { 187, N25,   "Lower" },
    { 189, N25,   "Nomad" },
    { 192, VSG,   "Saribitotachi no Waltz" },
    { 193, MMJ,   "Worldwide Wander" },
    { 196, LEO,   "Order Made" },
    { 203, N25,   "Tricologe" },
    { 207, LEO,   "Peaky Peaky" },
    { 209, MMJ,   "Metamo Re:born" },
    { 211, MMJ,   "IF" },
    { 212, WxS,   "Hoshizora no Melody" },
    { 217, VBS,   "Machi" },
    { 224, WxS,   "88☆彡" },
    { 230, OTHER, "Salamander" },
    { 231, OTHER, "Identity" },
    { 232, OTHER, "Aoiro Enogu" },
    { 233, OTHER, "Cosmospice" },
    { 234, OTHER, "Tokugawa Cup Noodle Kinshirei" },
    { 235, OTHER, "Journey" },
    { 236, LEO,   "Voices" },
    { 237, N25,   "Kimi no Yoru wo Kure" },
    { 239, VBS,   "Gekkou" },
    { 244, VBS,   "Awake Now" },
    { 248, N25,   "bug" },
    { 252, MMJ,   "DREAM PLACE" },
    { 257, LEO,   "Teratera" },
    { 259, LEO,   "the WALL" },
    { 264, MMJ,   "Parasol Cider" },
    { 267, VBS,   "Kashika" },
    { 280, VBS,   "Utsuro wo Aogu" },
    { 282, WxS,   "Hoshizora Orchestra" },
    { 285, VSG,   "ÅMARA" },
    { 287, MMJ,   "Watashi wa, Watashitachi wa" },
    { 290, WxS,   "Donna Ketsumatsu ga Onozomi dai?" },
    { 295, MMJ,   "Float Planner" },
    { 300, N25,   "Samsa" },
    { 302, LEO,   "Hurray" },
    { 304, N25,   "I Nandesu" },
    { 308, MMJ,   "Momoiro no Kagi" },
    { 310, LEO,   "Flyway" },
    { 316, VBS,   "Hitsuji ga Ippiki" },
    { 324, WxS,   "Hakoniwa no Coral" },
    { 333, WxS,   "Mr. Showtime" },
    { 336, OTHER, "Be The MUSIC!" },
    { 345, N25,   "Engeki" },
    { 351, LEO,   "Aioi" },
    { 353, N25,   "kitty" },
    { 356, VBS,   "Realize" },
    { 366, OTHER, "NEO" },
    { 368, VSG,   "I'm Mine" },
    { 373, VBS,   "Gekokujou" },
    { 374, MMJ,   "Teammate" },
    { 375, LEO,   "Hoshi wo Tsunagu" },
    { 383, LEO,   "purpose" },
    { 384, N25,   "Twilight Light" },
    { 386, WxS,   "Kirapipi★Kirapika" },
    { 393, VSG,   "Un-Lock" },
    { 394, VSG,   "Bottle Cake" },
    { 397, WxS,   "filament fever" },
    { 398, VBS,   "Beyond the way" },
    { 400, MMJ,   "Warera Stain Busters!" },
    { 404, VBS,   "blender" },
    { 405, MMJ,   "MOTTO!!!" },
    { 406, VSG,   "ARQETYPE" },
    { 409, N25,   "25-ji no Jounetsu" },
    { 411, WxS,   "Sekai wo Terasu Tetrad" },
    { 416, VSG,   "limbo" },
    { 421, VBS,   "CRAZY" },
    { 422, MMJ,   "JUMPIN’ OVER !" },
    { 423, LEO,   "Regulus" },
    { 424, LEO,   "Integral" },
    { 427, VSG,   "Yuukou, 1/f no Yurameki" },
    { 428, VSG,   "Tokimeki Jet Coaster" },
    { 429, MMJ,   "Hug" },
    { 440, VSG,   "Showtime×Audience" },
    { 442, LEO,   "Suresure" },
    { 445, VSG,   "Twilight Melody" },
    { 450, WxS,   "Opera! Space Opera!" },
    { 452, WxS,   "CYBERPUNK DEAD BOY" },
    { 457, MMJ,   "Supernova" },
    { 460, VSG,   "LEADER" },
    { 465, VSG,   "Jouou" },
    { 471, VBS,   "ULTRA C" },
    { 472, WxS,   "Seibai ItaAAAAAsu!" },
    { 474, MMJ,   "Killer" },
    { 478, VBS,   "Fuel" },
    { 489, OTHER, "Neppuu" },
    { 492, N25,   "Watashi wa Ame" },
    { 497, VBS,   "Rekka" },
    { 498, MMJ,   "Hashiru! Tooku! Todoku!" },
    { 500, N25,   "Yoka ni Mitorete" },
    { 507, N25,   "Empurple" },
    { 508, VBS,   "Haven" },
    { 514, VSG,   "FAKE HEART" },
    { 519, VSG,   "Natsuyo no Uta" },
    { 524, LEO,   "Soredemo Bokura wa Utau Koto wo Yamenai" },
    { 527, VSG,   "Unpoison" },
    { 538, WxS,   "All-Save Challenge" },
    { 539, MMJ,   "Eleventh" },
    { 540, N25,   "Nihil-san" },
    { 543, VSG,   "Seimeisei Syndrome" },
    { 546, LEO,   "Sono Oto ga Naru Nara" },
    { 548, WxS,   "Boku no Kami-sama" },
    { 549, N25,   "Bake no Hana" },
    { 555, OTHER, "Fusion" },
    { 560, WxS,   "EYELID" },
    { 564, N25,   "Soko ni Aru, Hikari." },
    { 570, LEO,   "Star" },
    { 572, N25,   "Kazatte" },
    { 573, VSG,   "Hajimari no Mirai" },
    { 574, LEO,   "SToRY" },
    { 575, MMJ,   "FUN!!" },
    { 576, VBS,   "Fire Dance" },
    { 577, WxS,   "Smile*Symphony" },
    { 578, VSG,   "Hello, SEKAI" },
    { 579, OTHER, "Worlders" },
    { 582, MMJ,   "ANTI YOU" },
    { 583, VBS,   "Accelerate" },
    { 585, OTHER, "pentatonic" },
    { 596, N25,   "D/N/A" },
    { 597, N25,   "Sono E no Namae wa" },
    { 600, WxS,   "Yuke" },
    { 602, VSG,   "ELECTRIC WEEKEND ZONE" },
    { 605, LEO,   "Sympathy" },
    { 610, MMJ,   "Polar Star" },
    { 630, N25,   "Koufuku Kei" },
    { 634, VBS,   "Kousenka" },
    { 635, MMJ,   "Ari no Mama no Story wo" },
    { 642, LEO,   "Kono Manma de Ikou" },
    { 646, LEO,   "Toumei na Palette" },
    { 649, WxS,   "Sayonara Tengoku Mata Kite Jigoku" },
    { 659, MMJ,   "Anata no Sora ga Naku no Nara" },
    { 660, WxS,   "Tobidase! Wonder-Pyoi" },
    { 662, N25,   "Kokuhaku" },
    { 668, VSG,   "Nekuratune Circus" },
    { 671, VSG,   "Kaijuu ni Naritai" },
    { 673, VSG,   "New Worlds" },
    { 674, VSG,   "MASTER Kounan'ido Gakkyoku Medley" },
    { 675, VSG,   "ProSEKA ULTIMATE Gakkyoku Medley" },
    { 676, VSG,   "Shuunen Kinen Kounan'ido Kakioroshi Gakkyoku Medley" },
    { 679, VBS,   "CRASH THE PARTY" },
    { 681, LEO,   "Hoshi ni Ichiban Chikai Basho" },
    { 683, MMJ,   "Colorful Foundation" },
    { 684, VBS,   "Fighter" },
    { 695, LEO,   "Hanamusubi" },
    { 701, VSG,   "Chu! Future☆Express!" },
    { 716, VBS,   "Touka Suru Ondo" },
    { 735, WxS,   "Kugutsu no Utsutsu" },
    { 740, VBS,   "Uka" },
    /* Contest Songs */
    { no, VSG,    "Hatsune Kyousoukyoku Dai 01-ban \"Suisei\"" },
    { no, VSG,    "Kowarechatta!!" },
    { no, VSG,    "Marude Nijuu Furiko no Sekai!" },
    { 82, VSG,    "alive" },
    { 11009, VSG, "Dīcǎidù Jìshì" },
    { 128, VSG,   "Brand New Day" },
    { 137, VSG,   "Hana wo Utau" },
    { 151, VSG,   "Utakata Mirai" },
    { 165, VSG,   "Sou Datta!!" },
    { 185, VSG,   "Sick of House!" },
    { 197, VSG,   "Last Score" },
    { 215, VSG,   "Judas" },
    { 227, VSG,   "ONESELF" },
    { 254, VSG,   "Mikansei Sanka" },
    { 274, VSG,   "Soredemo Ii nda yo" },
    { 292, VSG,   "Ichi Ni no San de" },
    { 314, VSG,   "Hidamari no Setsuna" },
    { 315, VSG,   "What's up? Pop!" },
    { 329, VSG,   "YAMINABE!!!!" },
    { 332, VSG,   "Epilogue ni Kimi wa Inai" },
    { 338, VSG,   "Where shall we go?" },
    { 359, VSG,   "Namonaki Kakumei" },
    { 364, VSG,   "Eternal Aria" },
    { 370, VSG,   "Jinsei" },
    { 380, VSG,   "Stardust Medley" },
    { 382, VSG,   "Shinpaku Pairing" },
    { 399, VSG,   "Disco No.39" },
    { 408, VSG,   "CIRCUS PANIC!!!" },
    { 425, VSG,   "Cool Me Down" },
    { 426, VSG,   "On&On" },
    { 444, VSG,   "Syndrome" },
    { 446, VSG,   "Overcode" },
    { 468, VSG,   "Juurokusai no Shinzou" },
    { 481, VSG,   "Meikyoushisui" },
    { 486, VSG,   "OGYARINIZER" },
    { 487, VSG,   "Daijobu Desu ka?" },
    { 488, VSG,   "Memoria" },
    { 496, VSG,   "Silver Collector" },
    { 504, VSG,   "I know Ai Nou." },
    { 512, VSG,   "Gousei Suru Mirai" },
    { 517, VSG,   "Merry-Go-Round" },
    { 526, VSG,   "Suisei no Kuni" },
    { 532, VSG,   "Layer Note" },
    { 545, VSG,   "Nouten" },
    { 553, VSG,   "Parry" },
    { 565, VSG,   "Natsu ni Toumei" },
    { 569, VSG,   "Secret Seeker" },
    { 587, VSG,   "Rule Book" },
    { 588, VSG,   "Planet Hero" },
    { 608, VSG,   "Hoshizora Melancholia" },
    { 626, VSG,   "Fish and Tips" },
    { 633, VSG,   "Niwashi no Ohanashi ni Yoru to" },
    { 636, VSG,   "Explore" },
    { 637, VSG,   "Waraetara Ee Yan!" },
    { 647, VSG,   "SANchi Chokusou" },
    { 655, VSG,   "lily-lala" },
    { 656, VSG,   "Blood Doll" },
    { 677, VSG,   "Abelia" },
    { 678, VSG,   "Kindokei" },
    { 691, VSG,   "0.0000034" },
    { 696, VSG,   "Dream Kiss" },
    { 697, VSG,   "Internet Junk Junkie" },
    { 720, VSG,   "Aria" },
    { 732, VSG,   "Tenran no Ice Heaven" },
    { 737, VSG,   "Doukaai" },
    { 738, VSG,   "Strata de Machiawase" },
  });
